name: ba_dbtvault
profile: ba_dbtvault
version: '5.3.0'
require-dbt-version: ['>=1.0.0', '<2.0.0']
config-version: 2

analysis-paths:
  - analysis
clean-targets:
  - target
seed-paths:
  - seeds
macro-paths:
  - macros
model-paths:
  - models
test-paths:
  - tests
target-path: target

vars:
  load_date: '2020-01-01'

models:
  ba_dbtvault:
    raw_stage:
      tags:
        - 'raw'
      materialized: view
    stage:
      tags:
        - 'stage'
      enabled: true
      materialized: view
    raw_vault:
      tags:
        - 'raw_vault'
      materialized: incremental
      hubs:
        tags:
          - 'hub'
      links:
        tags:
          - 'link'
      sats:
        tags:
          - 'satellite'
      t_links:
        tags:
          - 't_link'

clean-targets:
    - target
    - dbt_packages
    - logs
